config/routes.rb
Rails.application.routes.draw do
  get 'test/testVar'
  get 'test/getTeamList'
  post 'test/saveTeamPicks'

  resources :team_instances
  resources :teams
  resources :game_picks
  resources :random_picks
  resources :suicide_picks
  resources :user_entries
  resources :users
  resources :quadrants
  resources :games
  resources :brackets
  resources :challenges

  root :to => 'home#index'

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base

	belongs_to :challenge
	has_many :team_instances
	has_many :games
	has_many :quadrants

end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  before_action :set_bracket, only: [:show, :edit, :update, :destroy, :testVar]

  # GET /brackets
  # GET /brackets.json
  def index
    @brackets = Bracket.all
  end

  # GET /brackets/1
  # GET /brackets/1.json
  def show
  end

  # GET /brackets/new
  def new
    @bracket = Bracket.new
  end

  # GET /brackets/1/edit
  def edit
  end

  # POST /brackets
  # POST /brackets.json
  def create
    @bracket = Bracket.new(bracket_params)

    respond_to do |format|
      if @bracket.save
        format.html { redirect_to @bracket, notice: 'Bracket was successfully created.' }
        format.json { render :show, status: :created, location: @bracket }
      else
        format.html { render :new }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brackets/1
  # PATCH/PUT /brackets/1.json
  def update
    respond_to do |format|
      if @bracket.update(bracket_params)
        format.html { redirect_to @bracket, notice: 'Bracket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bracket }
      else
        format.html { render :edit }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brackets/1
  # DELETE /brackets/1.json
  def destroy
    @bracket.destroy
    respond_to do |format|
      format.html { redirect_to brackets_url, notice: 'Bracket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bracket
      @bracket = Bracket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracket_params
      params.require(:bracket).permit(:challenge_id)
    end
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/views/brackets/_form.html.erb
<%= form_for(@bracket) do |f| %>
  <% if @bracket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bracket.errors.count, "error") %> prohibited this bracket from being saved:</h2>

      <ul>
      <% @bracket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :challenge_id %><br>
    <%= f.number_field :challenge_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brackets/edit.html.erb
<h1>Editing Bracket</h1>

<%= render 'form' %>

<%= link_to 'Show', @bracket %> |
<%= link_to 'Back', brackets_path %>

app/views/brackets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brackets</h1>

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brackets.each do |bracket| %>
      <tr>
        <td><%= bracket.challenge.year %></td>
        <td><%= link_to 'Show', bracket %></td>
        <td><%= link_to 'Edit', edit_bracket_path(bracket) %></td>
        <td><%= link_to 'Destroy', bracket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bracket', new_bracket_path %>

app/views/brackets/new.html.erb
<h1>New Bracket</h1>

<%= render 'form' %>

<%= link_to 'Back', brackets_path %>

app/views/brackets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenge:</strong>
  <%= @bracket.challenge_id %>
</p>

<%= link_to 'Edit', edit_bracket_path(@bracket) %> |
<%= link_to 'Back', brackets_path %>