config/routes.rb
Rails.application.routes.draw do
  get 'test/testVar'
  get 'test/getTeamList'
  post 'test/saveTeamPicks'

  resources :team_instances
  resources :teams
  resources :game_picks
  resources :random_picks
  resources :suicide_picks
  resources :user_entries
  resources :users
  resources :quadrants
  resources :games
  resources :brackets
  resources :challenges

  root :to => 'home#index'

end

app/models/quadrant.rb
class Quadrant < ActiveRecord::Base
	validates :order, :presence => true
	validates :name, :presence => true

	belongs_to :bracket
	has_one :challenge, :through => :bracket
	has_many :games
	has_many :team_instances

	accepts_nested_attributes_for :bracket
	
end

app/controllers/quadrants_controller.rb
class QuadrantsController < ApplicationController
  before_action :set_quadrant, only: [:show, :edit, :update, :destroy]

  # GET /quadrants
  # GET /quadrants.json
  def index
    @quadrants = Quadrant.all
  end

  # GET /quadrants/1
  # GET /quadrants/1.json
  def show
  end

  # GET /quadrants/new
  def new
    @quadrant = Quadrant.new
  end

  # GET /quadrants/1/edit
  def edit
  end

  # POST /quadrants
  # POST /quadrants.json
  def create
    @quadrant = Quadrant.new(quadrant_params)

    respond_to do |format|
      if @quadrant.save
        format.html { redirect_to @quadrant, notice: 'Quadrant was successfully created.' }
        format.json { render :show, status: :created, location: @quadrant }
      else
        format.html { render :new }
        format.json { render json: @quadrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quadrants/1
  # PATCH/PUT /quadrants/1.json
  def update
    respond_to do |format|
      if @quadrant.update(quadrant_params)
        format.html { redirect_to @quadrant, notice: 'Quadrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @quadrant }
      else
        format.html { render :edit }
        format.json { render json: @quadrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quadrants/1
  # DELETE /quadrants/1.json
  def destroy
    @quadrant.destroy
    respond_to do |format|
      format.html { redirect_to quadrants_url, notice: 'Quadrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quadrant
      @quadrant = Quadrant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quadrant_params
      params.require(:quadrant).permit(:bracket_id, :name, :order)
    end
end

app/helpers/quadrants_helper.rb
module QuadrantsHelper
end

app/views/quadrants/_form.html.erb
<%= form_for(@quadrant) do |f| %>
  <% if @quadrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quadrant.errors.count, "error") %> prohibited this quadrant from being saved:</h2>

      <ul>
      <% @quadrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bracket_id %><br>
    <%= f.select :bracket_id, Bracket.all.collect {|x| [x.challenge.year, x.id]}, {:prompt => "Select a year"} %>
  </div>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.select :order, [1,2,3,4].collect {|x| [x, x]}, {:prompt => "Select an order"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quadrants/edit.html.erb
<h1>Editing Quadrant</h1>

<%= render 'form' %>

<%= link_to 'Show', @quadrant %> |
<%= link_to 'Back', quadrants_path %>

app/views/quadrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quadrants</h1>

<table>
  <thead>
    <tr>
      <th>Bracket</th>
      <th>Name</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quadrants.each do |quadrant| %>
      <tr>
        <td><%= quadrant.challenge.year %></td>
        <td><%= quadrant.name %></td>
        <td><%= quadrant.order %></td>
        <td><%= link_to 'Show', quadrant %></td>
        <td><%= link_to 'Edit', edit_quadrant_path(quadrant) %></td>
        <td><%= link_to 'Destroy', quadrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quadrant', new_quadrant_path %>

app/views/quadrants/new.html.erb
<h1>New Quadrant</h1>

<%= render 'form' %>

<%= link_to 'Back', quadrants_path %>

app/views/quadrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bracket:</strong>
  <%= @quadrant.bracket.challenge.year %>
</p>

<p>
  <strong>Name:</strong>
  <%= @quadrant.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @quadrant.order %>
</p>

<%= link_to 'Edit', edit_quadrant_path(@quadrant) %> |
<%= link_to 'Back', quadrants_path %>