config/routes.rb
Rails.application.routes.draw do
  get 'test/testVar'
  get 'test/getTeamList'
  post 'test/saveTeamPicks'

  resources :team_instances
  resources :teams
  resources :game_picks
  resources :random_picks
  resources :suicide_picks
  resources :user_entries
  resources :users
  resources :quadrants
  resources :games
  resources :brackets
  resources :challenges

  root :to => 'home#index'

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base

	belongs_to :challenge
	has_many :team_instances
	has_many :games
	has_many :quadrants

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base

	has_many :user_entries
	has_one :bracket

	has_many :games, through: :bracket 
	has_many :quadrants, through: :bracket

	has_many :team_instances, :through => :bracket
end

app/models/game.rb
class Game < ActiveRecord::Base

	belongs_to :home_team, :class_name => "TeamInstance", :foreign_key => :home_team_id
	belongs_to :away_team, :class_name => "TeamInstance", :foreign_key => :away_team_id
	
	belongs_to :quadrant
	belongs_to :bracket
	#belongs_to :challenge, through: :bracket
	belongs_to :challenge

	def finished
		(((half.to_i == 2) || (half == "OT")) && (game_timer.length > 0) && (game_timer.to_i == 0))
	end

	def winner
		if (self.finished)
			if (self.home_team_score > self.away_team_score)
				self.home_team
			else
				self.away_team
			end
		end
	end


end

app/models/game_pick.rb
class GamePick < ActiveRecord::Base
	belongs_to :user_entry
	belongs_to :team_instance
end

app/models/quadrant.rb
class Quadrant < ActiveRecord::Base
	validates :order, :presence => true
	validates :name, :presence => true

	belongs_to :bracket
	has_one :challenge, :through => :bracket
	has_many :games
	has_many :team_instances

	accepts_nested_attributes_for :bracket
	
end

app/models/random_pick.rb
class RandomPick < ActiveRecord::Base
	belongs_to :user_entry
	has_many :team_instances
end

app/models/suicide_pick.rb
class SuicidePick < ActiveRecord::Base

	belongs_to :user_entry
	has_many :team_instances
	
end

app/models/team.rb
class Team < ActiveRecord::Base

	has_many :team_instances
end

app/models/team_instance.rb
class TeamInstance < ActiveRecord::Base

	belongs_to :team
	belongs_to :suicide_pick
	belongs_to :random_pick
	has_many :game_picks
	belongs_to :bracket
	belongs_to :quadrant

	has_one :challenge, :through => :bracket

	has_many :home_teams, :class_name => "Game", :foreign_key => :home_team_id
	has_many :away_teams, :class_name => "Game", :foreign_key => :away_team_id


	def bracket_seed
		((self.quadrant.order-1)*16)+(self.seed)
	end


end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :user_entries

	def fullname
		first_name + " " + last_name
	end

end

app/models/user_entry.rb
class UserEntry < ActiveRecord::Base

	belongs_to :challenge
	belongs_to :user

	has_many :suicide_picks
	has_many :random_picks
	has_many :game_picks

	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /home
  # GET /home.json
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end



  
end

app/controllers/user_entries_controller.rb
class UserEntriesController < ApplicationController
  before_action :set_user_entry, only: [:show, :edit, :update, :destroy]

  # GET /user_entries
  # GET /user_entries.json
  def index
    @user_entries = UserEntry.all
  end

  # GET /user_entries/1
  # GET /user_entries/1.json
  def show
  end

  # GET /user_entries/new
  def new
    @user_entry = UserEntry.new
  end

  # GET /user_entries/1/edit
  def edit
  end

  # POST /user_entries
  # POST /user_entries.json
  def create
    @user_entry = UserEntry.new(user_entry_params)

    respond_to do |format|
      if @user_entry.save
        #byebug

        #seeding the random picks
        (1..8).each do |r|
          RandomPick.new({user_entry_id: @user_entry.id}).save
        end

        #seeding the suicide pick
        SuicidePick.new({user_entry_id: @user_entry.id}).save

        #seeding the game picks
        @user_entry.challenge.team_instances.each do |t|
          GamePick.new({user_entry_id: @user_entry.id, team_instance_id: t, round: 0}).save
        end

        format.html { redirect_to @user_entry, notice: 'User entry was successfully created.' }
        format.json { render :show, status: :created, location: @user_entry }
      else
        format.html { render :new }
        format.json { render json: @user_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_entries/1
  # PATCH/PUT /user_entries/1.json
  def update
    respond_to do |format|
      if @user_entry.update(user_entry_params)
        format.html { redirect_to @user_entry, notice: 'User entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_entry }
      else
        format.html { render :edit }
        format.json { render json: @user_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_entries/1
  # DELETE /user_entries/1.json
  def destroy
    @user_entry.destroy
    respond_to do |format|
      format.html { redirect_to user_entries_url, notice: 'User entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_entry
      @user_entry = UserEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_entry_params
      params.require(:user_entry).permit(:user_id, :challenge_id, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/game_picks_helper.rb
module GamePicksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/quadrants_helper.rb
module QuadrantsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/user_entries_helper.rb
module UserEntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_entries/_form.html.erb
<%= form_for(@user_entry) do |f| %>
  <% if @user_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_entry.errors.count, "error") %> prohibited this user_entry from being saved:</h2>

      <ul>
      <% @user_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <!--%= f.collection_select :user_id, User.where("active = true").collect, :id, :fullname, :prompt => "Select a user" %-->
    <%= f.collection_select :user_id, User.all.collect, :id, :fullname, :prompt => "Select a user" %>

  </div>
  <div class="field">
    <%= f.label :challenge_id %><br>
    <%= f.collection_select :challenge_id, Challenge.all.order('year ASC'), :id, :year, :prompt => "Select a challenge" %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_entries/edit.html.erb
<h1>Editing User Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_entry %> |
<%= link_to 'Back', user_entries_path %>

app/views/user_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Entries</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Challenge</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_entries.each do |user_entry| %>
      <tr>
        <td><%= user_entry.user.first_name + " " + user_entry.user.last_name %></td>
        <td><%= user_entry.challenge.year %></td>
        <td><%= user_entry.active %></td>
        <td><%= link_to 'Show', user_entry %></td>
        <td><%= link_to 'Edit', edit_user_entry_path(user_entry) %></td>
        <td><%= link_to 'Destroy', user_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User entry', new_user_entry_path %>

app/views/user_entries/new.html.erb
<h1>New User Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', user_entries_path %>

app/views/user_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_entry.user.first_name + " " + @user_entry.user.last_name %>
</p>

<p>
  <strong>Challenge:</strong>
  <%= @user_entry.challenge.year %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user_entry.active %>
</p>

<%= link_to 'Edit', edit_user_entry_path(@user_entry) %> |
<%= link_to 'Back', user_entries_path %>