config/routes.rb
Rails.application.routes.draw do
  get 'test/testVar'
  get 'test/getTeamList'
  post 'test/saveTeamPicks'

  resources :team_instances
  resources :teams
  resources :game_picks
  resources :random_picks
  resources :suicide_picks
  resources :user_entries
  resources :users
  resources :quadrants
  resources :games
  resources :brackets
  resources :challenges

  root :to => 'home#index'

end

app/models/game_pick.rb
class GamePick < ActiveRecord::Base
	belongs_to :user_entry
	belongs_to :team_instance
end

app/controllers/game_picks_controller.rb
class GamePicksController < ApplicationController
  before_action :set_game_pick, only: [:show, :edit, :update, :destroy]

  # GET /game_picks
  # GET /game_picks.json
  def index
    @game_picks = GamePick.all
  end

  # GET /game_picks/1
  # GET /game_picks/1.json
  def show
  end

  # GET /game_picks/new
  def new
    @game_pick = GamePick.new
  end

  # GET /game_picks/1/edit
  def edit
  end

  # POST /game_picks
  # POST /game_picks.json
  def create
    @game_pick = GamePick.new(game_pick_params)

    respond_to do |format|
      if @game_pick.save
        format.html { redirect_to @game_pick, notice: 'Game pick was successfully created.' }
        format.json { render :show, status: :created, location: @game_pick }
      else
        format.html { render :new }
        format.json { render json: @game_pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_picks/1
  # PATCH/PUT /game_picks/1.json
  def update
    respond_to do |format|
      if @game_pick.update(game_pick_params)
        format.html { redirect_to @game_pick, notice: 'Game pick was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_pick }
      else
        format.html { render :edit }
        format.json { render json: @game_pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_picks/1
  # DELETE /game_picks/1.json
  def destroy
    @game_pick.destroy
    respond_to do |format|
      format.html { redirect_to game_picks_url, notice: 'Game pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_pick
      @game_pick = GamePick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_pick_params
      params.require(:game_pick).permit(:user_entry_id, :team_instance_id, :round)
    end
end

app/helpers/game_picks_helper.rb
module GamePicksHelper
end

app/views/game_picks/_form.html.erb
<%= form_for(@game_pick) do |f| %>
  <% if @game_pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_pick.errors.count, "error") %> prohibited this game_pick from being saved:</h2>

      <ul>
      <% @game_pick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_entry_id %><br>
    <%= f.select :user_entry_id, UserEntry.all.collect {|x| [x.user.fullname, x.id]}, {:prompt => "Select a User"} %>
  </div>
  <div class="field">
    <%= f.label :team_instance_id %><br>
    <%= f.select :team_instance_id, TeamInstance.all.collect {|x| [x.team.name, x.id]}, {:prompt => "Select a Team"} %>
  </div>
  <div class="field">
    <%= f.label :round %><br>
    <%= f.select :round, (1..6).collect {|x| [x, x]}, {:prompt => "Select an order"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_picks/edit.html.erb
<h1>Editing Game Pick</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_pick %> |
<%= link_to 'Back', game_picks_path %>

app/views/game_picks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Game Picks</h1>

<table>
  <thead>
    <tr>
      <th>User entry</th>
      <th>Team instance</th>
      <th>Round</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_picks.each do |game_pick| %>
      <tr>
        <td><%= "#{game_pick.user_entry.user.fullname} (#{game_pick.user_entry.challenge.year})" %></td>
        <td class="center"><%= raw(game_pick.team_instance_id ? game_pick.team_instance.team.name : "<span class='italics'>N/A</span>") %></td>
        <td class="center"><%= game_pick.round.to_i %></td>
        <td><%= link_to 'Show', game_pick %></td>
        <td><%= link_to 'Edit', edit_game_pick_path(game_pick) %></td>
        <td><%= link_to 'Destroy', game_pick, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game pick', new_game_pick_path %>

app/views/game_picks/new.html.erb
<h1>New Game Pick</h1>

<%= render 'form' %>

<%= link_to 'Back', game_picks_path %>

app/views/game_picks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User entry:</strong>
  <%= @game_pick.user_entry.user.fullname %>
</p>

<p>
  <strong>Team instance:</strong>
  <%= raw(@game_pick.team_instance_id ? @game_pick.team_instance.team.name : "<span class='italics'>N/A</span>") %>
</p>

<p>
  <strong>Round:</strong>
  <%= @game_pick.round %>
</p>

<%= link_to 'Edit', edit_game_pick_path(@game_pick) %> |
<%= link_to 'Back', game_picks_path %>